name: CI

on:
  # Events that trigger workflows
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: debug
        run: |
          echo "github.event_name: ${{ github.event_name }}"
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"

      - name: github-script
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const message = 'Hello!';

            console.log('context:', context);
            console.log('github:', github);
            console.log('github.ref:', github.ref);
            console.log('github.ref_name:', github.ref_name);

            // 以下は、権限の設定を行わないとエラーになる。
            // https://github.com/gipcompany/workflow_cove/settings/actions
            // Workflow permissions で、 `Read repository contents and packages permissions` から `Read and write permissions` に変更し、Saveする。
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
