name: CI

on:
  # Events that trigger workflows
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: debug
        run: 'echo "github.ref_name: ${{ github.ref_name }}"'

      - name: github-script
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const message = 'Hello!';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
