name: CI

on:
  # Events that trigger workflows
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: debug
        run: 'echo "github.ref_name: ${{ github.ref_name }}"'
